<a href="https://colab.research.google.com/github/aunyarit2005-hash/Super-AI-Engineer-Season-6/blob/main/mini_Hackathon_Form_Data_to_Insight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📑 Data import and cleaning

**📑 1. การจัดการข้อมูลซ้ำ (Handling Duplicates)**

สิ่งที่ทำ: ค้นหาและลบแถวที่หน้าตาเหมือนกันเป๊ะออก

สาเหตุ: เพราะบางทีข้อมูลอาจจะเบิ้ลมาจากการรวมไฟล์ ถ้าไม่ลบออก ยอดเงินรวมจะสูงเกินจริงจนน่าตกใจ!

---

**🧩 2. การเติมค่าที่หายไป (Handling Missing Values / Imputation)**

สิ่งที่ทำ: ซ่อมแซมส่วนที่แหว่งไป เช่น ถ้ามีชื่อประเทศ countryNameTH แต่ดันลืมใส่ countryID เราก็ไปหามาเติมให้เต็ม

สาเหตุ: ข้อมูลที่ขาดหายไปก็เหมือนจิ๊กซอว์ที่ต่อไม่เสร็จ 🧩 ถ้าปล่อยไว้ ข้อมูลประเทศนั้นจะหายไปเลยตอนเราสรุปผล 🔍

---

**🔢 3. การจัดการรหัสที่เข้าใจยาก (Data Encoding)**

เปลี่ยนเลข 1 ➡️ Import (นำเข้า) และเลข 2 ➡️ Export (ส่งออก) 🌐

สาเหตุ: จะได้ไม่ต้องคอยเปิดคู่มือดูว่าเลขไหนคืออะไร ช่วยให้เรา ดูปุ๊บรู้ปั๊บว่าฝั่งไหนนำเข้าหรือส่งออก! 💡

---

**🧹 4. การกรองข้อมูลที่ไม่สมบูรณ์ (Garbage Data Filtering)**

สิ่งที่ทำ: กำจัดค่าว่างเปล่า (blank) หรือ Error จาก Excel อย่าง #NAME! 🧼

สาเหตุ: ข้อมูลพวกนี้คือ "นอยซ์" (Noise) ที่ทำให้ Insight ของเราเพี้ยน ถ้าเอาขยะมาทำกราฟ ผลลัพธ์ที่ได้ก็จะเป็นขยะตามไปด้วย

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('import_export.csv')

In [ ]:
df #ลองเปิดดูข้อมูลเบื่องต้นก่อนนำไปวิเคราะห์

Warning: total number of rows (42057) exceeds max_rows (20000). Falling back to pandas display.

,year,month,heading11,countryID,countryNameTH,weight,quantity,price,tradeflow,productDetailEN,productDetailTH,ETL_DATE
0,2568,8,1062000002,BJ,เบนิน,33,90,48080,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
1,2568,8,1062000002,MU,มอริเชียส,10,50,44147,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
2,2568,8,1062000002,BR,บราซิล,8,150,47068,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
3,2568,8,1062000002,EG,อียิปต์,315,100,225663,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
4,2568,9,1062000002,KE,เคนยา,49,200,74954,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
...,...,...,...,...,...,...,...,...,...,...,...,...
42052,2568,7,3099090000,HK,ฮ่องกง,4,1,103182,2,Of otheraquatic i nvertebrates,ของสัตว์น้ำที่ไม่มีกระดูกสันหลังอื่น ๆ,12/3/2026 5:59
42053,2568,5,12122930090,LA,ลาว,100,10,14347,2,For seaweeds imported for used in the manufact...,เฉพาะสาหร่ายทะเล นําเข้ามาเพื่อใช้ในอุตสาหกรรม...,12/3/2026 5:59
42054,2568,8,12122930090,LA,ลาว,50,5,6816,2,For seaweeds imported for used in the manufact...,เฉพาะสาหร่ายทะเล นําเข้ามาเพื่อใช้ในอุตสาหกรรม...,12/3/2026 5:59
42055,2568,9,12122930090,LA,ลาว,20,2,2536,2,For seaweeds imported for used in the manufact...,เฉพาะสาหร่ายทะเล นําเข้ามาเพื่อใช้ในอุตสาหกรรม...,12/3/2026 5:59
42056,2568,11,12122930090,LA,ลาว,50,5,6816,2,For seaweeds imported for used in the manufact...,เฉพาะสาหร่ายทะเล นําเข้ามาเพื่อใช้ในอุตสาหกรรม...,12/3/2026 5:59

In [ ]:
df_original = df.copy() #เพื่อใช้ในการตรวจสอบค่าที่เปลี่ยนไปหลังจากเปลี่ยนแปลงค่าแล้ว

เช็คข้อมูลซ้ำเบื่องต้น

In [ ]:
# 1. นับจำนวนแถวที่ซ้ำกันทั้งหมด
duplicate_count = df.duplicated().sum()
print(f"พบข้อมูลซ้ำกันทั้งแถวทั้งหมด: {duplicate_count} รายการ")

# 2. ขอดูตัวอย่างแถวที่ซ้ำ (เพื่อให้เห็นภาพว่าซ้ำยังไง)
if duplicate_count > 0:
    display(df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head(10))

พบข้อมูลซ้ำกันทั้งแถวทั้งหมด: 5 รายการ

,year,month,heading11,countryID,countryNameTH,weight,quantity,price,tradeflow,productDetailEN,productDetailTH,ETL_DATE
29924,2568,1,16055490000,HK,ฮ่องกง,7,1,82,2,Other,ปลาหมึกกระดองและปลาหมึกกล้วยอื่น ๆ ที่ไม่บรรจุ...,12/3/2026 5:59
30193,2568,1,16055490000,HK,ฮ่องกง,7,1,82,2,Other,ปลาหมึกกระดองและปลาหมึกกล้วยอื่น ๆ ที่ไม่บรรจุ...,12/3/2026 5:59
22194,2568,2,16041419000,CU,คิวบา,14400,1200,1929660,2,#NAME?,ปลาทูน่า สคิปแจกและแอตแลนติกโบนิโตอื่นๆ ที่บรร...,12/3/2026 5:59
22236,2568,2,16041419000,CU,คิวบา,14400,1200,1929660,2,#NAME?,ปลาทูน่า สคิปแจกและแอตแลนติกโบนิโตอื่นๆ ที่บรร...,12/3/2026 5:59
30067,2568,4,16055490000,HK,ฮ่องกง,3,1,40,2,Other,ปลาหมึกกระดองและปลาหมึกกล้วยอื่น ๆ ที่ไม่บรรจุ...,12/3/2026 5:59
30084,2568,4,16055490000,HK,ฮ่องกง,3,1,40,2,Other,ปลาหมึกกระดองและปลาหมึกกล้วยอื่น ๆ ที่ไม่บรรจุ...,12/3/2026 5:59
40953,2568,8,16051014090,HK,ฮ่องกง,1,1,128,2,Other,ปู อื่น ๆ,12/3/2026 5:59
40958,2568,8,16051014090,HK,ฮ่องกง,1,1,128,2,Other,ปู อื่น ๆ,12/3/2026 5:59
23884,2568,12,16041419000,HK,ฮ่องกง,1,1,32,2,#NAME?,ปลาทูน่า สคิปแจกและแอตแลนติกโบนิโตอื่นๆ ที่บรร...,12/3/2026 5:59
23891,2568,12,16041419000,HK,ฮ่องกง,1,1,32,2,#NAME?,ปลาทูน่า สคิปแจกและแอตแลนติกโบนิโตอื่นๆ ที่บรร...,12/3/2026 5:59

In [ ]:
# กำหนดคอลัมน์ที่บ่งบอกว่าเป็น "รายการเดียวกัน"
subset_cols = ['year', 'month', 'heading11', 'countryID', 'weight', 'quantity', 'price', 'tradeflow']

logical_dup_count = df.duplicated(subset=subset_cols).sum()
print(f"พบข้อมูลซ้ำ (ไม่รวม ETL_DATE): {logical_dup_count} รายการ")

พบข้อมูลซ้ำ (ไม่รวม ETL_DATE): 5 รายการ

In [ ]:
# 1. ทำ Deep Copy ไว้ก่อนกันพลาด
df_cleaned = df.copy()

# 2. ลบข้อมูลซ้ำแบบเลือกเก็บรายการแรกไว้ (Keep 'first')
df_cleaned = df_cleaned.drop_duplicates(subset=subset_cols, keep='first')

# 3. ตรวจสอบจำนวนข้อมูลที่เหลือ
print(f"จำนวนข้อมูลเดิม: {len(df)} แถว")
print(f"จำนวนข้อมูลหลังลบตัวซ้ำ: {len(df_cleaned)} แถว")
print(f"ลบออกไปทั้งหมด: {len(df) - len(df_cleaned)} แถว")

# 4. แทนที่ df เดิมด้วยตัวที่คลีนแล้ว
df = df_cleaned

จำนวนข้อมูลเดิม: 42057 แถว
จำนวนข้อมูลหลังลบตัวซ้ำ: 42052 แถว
ลบออกไปทั้งหมด: 5 แถว

เช็คค่า Null ในแต่ละcolum

In [ ]:
null_count = df.isnull().sum()

print("จำนวนค่า Null ในแต่ละคอลัมน์:")
print(null_count)

จำนวนค่า Null ในแต่ละคอลัมน์:
year                0
month               0
heading11           0
countryID          25
countryNameTH       0
weight              0
quantity            0
price               0
tradeflow           0
productDetailEN     0
productDetailTH     0
ETL_DATE            0
dtype: int64

In [ ]:
# แสดงรายชื่อประเทศที่ countryID เป็นค่าว่าง
missing_ids = df[df['countryID'].isnull()]['countryNameTH'].unique()
print("ประเทศที่รหัสหายไปคือ:")
print(missing_ids)

ประเทศที่รหัสหายไปคือ:
['นามิเบีย']

In [ ]:
# 1. กรองเฉพาะแถวที่คอลัมน์ 'countryID' เป็นค่าว่าง (NaN)
rows_with_null = df[df['countryID'].isnull()]

# 2. แสดงข้อมูลทุกคอลัมน์ของแถวเหล่านั้น
rows_with_null

,year,month,heading11,countryID,countryNameTH,weight,quantity,price,tradeflow,productDetailEN,productDetailTH,ETL_DATE
5580,2568,3,3034100000,NaN,นามิเบีย,194755,194755,16318673,1,Albacore or longfinned tunas(Thunnus alalunga)...,ปลาแอลบาคอร์หรือทูน่าครีบยาวแช่เย็นจนแข็ง ไม่ร...,12/3/2026 5:59
6118,2568,7,3034200000,NaN,นามิเบีย,4452,4452,650647,1,Yellowfin tunas(Thunnus albacares) excluding l...,ปลาทูน่าครีบเหลืองแช่เย็นจนแข็ง ไม่รวมเนื้อปลา...,12/3/2026 5:59
6956,2568,12,3034400000,NaN,นามิเบีย,2500,2500,382881,1,Bigeyes tunas(Thunnus obesus) excluding livers...,ปลาบิกอายทูนา แช่เย็นจนแข็ง ไม่รวมตับและไข่(Bi...,12/3/2026 5:59
6991,2568,7,3034400000,NaN,นามิเบีย,69836,69836,10206334,1,Bigeyes tunas(Thunnus obesus) excluding livers...,ปลาบิกอายทูนา แช่เย็นจนแข็ง ไม่รวมตับและไข่(Bi...,12/3/2026 5:59
8366,2568,10,3039200000,NaN,นามิเบีย,15200,15200,859142,1,Shark fins,ครีบปลาฉลาม (หูฉลาม),12/3/2026 5:59
8380,2568,7,3039200000,NaN,นามิเบีย,26000,26000,1468115,1,Shark fins,ครีบปลาฉลาม (หูฉลาม),12/3/2026 5:59
8546,2568,7,3039900000,NaN,นามิเบีย,26000,921,863597,1,Other,หัวปลา หางปลา กระเพาะปลาและส่วนอื่นของปลาที่บร...,12/3/2026 5:59
20189,2568,1,16041311000,NaN,นามิเบีย,106560,266400,7914733,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20223,2568,2,16041311000,NaN,นามิเบีย,395945,1401120,31135949,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20251,2568,3,16041311000,NaN,นามิเบีย,159840,399600,11639781,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20290,2568,4,16041311000,NaN,นามิเบีย,159840,399600,11647440,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20325,2568,5,16041311000,NaN,นามิเบีย,35520,88800,2554395,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20357,2568,6,16041311000,NaN,นามิเบีย,301920,754800,21532455,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20402,2568,8,16041311000,NaN,นามิเบีย,86850,279600,6311066,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20433,2568,8,16041311000,NaN,นามิเบีย,38352,38352,1704890,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20436,2568,9,16041311000,NaN,นามิเบีย,254980,1022640,19744804,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20505,2568,10,16041311000,NaN,นามิเบีย,192575,580320,13744360,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20568,2568,12,16041311000,NaN,นามิเบีย,249410,1206480,20316242,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20609,2568,7,16041311000,NaN,นามิเบีย,301920,754800,21350181,2,Sardines sardinella and brisling or sprats pre...,ปลาซาร์ดีน ซาร์ดีนเนลล่าและปลาบริสลิงหรือปลาสแ...,12/3/2026 5:59
20945,2568,9,16041391000,NaN,นามิเบีย,38352,38352,1719436,2,Other Sardines prepared or preserved in airtig...,ปลาซาร์ดีน อื่นๆบรรจุภาชนะที่อากาศผ่านเข้าออกไ...,12/3/2026 5:59
20981,2568,10,16041391000,NaN,นามิเบีย,38352,38352,1679608,2,Other Sardines prepared or preserved in airtig...,ปลาซาร์ดีน อื่นๆบรรจุภาชนะที่อากาศผ่านเข้าออกไ...,12/3/2026 5:59
21024,2568,11,16041391000,NaN,นามิเบีย,38352,38352,1725682,2,Other Sardines prepared or preserved in airtig...,ปลาซาร์ดีน อื่นๆบรรจุภาชนะที่อากาศผ่านเข้าออกไ...,12/3/2026 5:59
21043,2568,12,16041391000,NaN,นามิเบีย,38352,38352,1712808,2,Other Sardines prepared or preserved in airtig...,ปลาซาร์ดีน อื่นๆบรรจุภาชนะที่อากาศผ่านเข้าออกไ...,12/3/2026 5:59
21084,2568,7,16041391000,NaN,นามิเบีย,57528,57528,2592210,2,Other Sardines prepared or preserved in airtig...,ปลาซาร์ดีน อื่นๆบรรจุภาชนะที่อากาศผ่านเข้าออกไ...,12/3/2026 5:59
38854,2568,1,3038919090,NaN,นามิเบีย,22702,22702,2033473,1,Other,ปลาอื่น ๆ แช่เย็นจนแข็ง,12/3/2026 5:59

จัดการค่าNull

In [ ]:
# 1. สร้าง Dictionary สำหรับจับคู่ชื่อประเทศ (ภาษาไทย) กับรหัสประเทศ (ID)
country_map = {
    'นามิเบีย': 'NA',
    'เนปาล': 'NP',
    'เซนต์คิตส์และเนวิส': 'KN',
    'หมู่เกาะแฟโร': 'FO',
    'แซมเบีย': 'ZM',
    'กรีนแลนด์': 'GL',
    'เซนต์วินเซนต์และเกรนาดีนส์': 'VC',
    'จิบูตี': 'DJ',
    'มอริเตเนีย': 'MR',
    'ซูรินาเม': 'SR',
    'เบลีซ': 'BZ',
    'เฟรนช์พอลินีเชีย': 'PF'
}

# 2. ใช้ฟังก์ชัน fillna ร่วมกับ map เพื่อเติมค่าเฉพาะจุดที่ว่าง
# โดยเราจะ map จากคอลัมน์ countryNameTH
df['countryID'] = df['countryID'].fillna(df['countryNameTH'].map(country_map))

# 3. ตรวจสอบผลลัพธ์
print(f"จำนวนค่าว่างที่เหลือใน countryID: {df['countryID'].isnull().sum()}")

# แสดง 5 แถวแรกที่เคยเป็นค่าว่าง (เพื่อเช็คว่าเปลี่ยนจริงไหม)
df[df['countryNameTH'].isin(country_map.keys())].head()

จำนวนค่าว่างที่เหลือใน countryID: 0

,year,month,heading11,countryID,countryNameTH,weight,quantity,price,tradeflow,productDetailEN,productDetailTH,ETL_DATE
10,2568,2,1062000002,ZM,แซมเบีย,45,450,128875,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
33,2568,7,1062000002,ZM,แซมเบีย,45,450,131268,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
36,2568,4,1062000002,NP,เนปาล,1,100,500,2,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
226,2568,1,3011191000,NP,เนปาล,4,1400,31840,2,#NAME?,ปลาคาร์ป สวยงามมีชีวิต (แฟนซีคาร์ป) (ไซพรีนสคา...,12/3/2026 5:59
256,2568,2,3011191000,NP,เนปาล,5,310,15080,2,#NAME?,ปลาคาร์ป สวยงามมีชีวิต (แฟนซีคาร์ป) (ไซพรีนสคา...,12/3/2026 5:59

เช็คค่าที่เปลี่ยนแปลงหลังจากการmapข้อมูล

In [ ]:
# 1. สร้าง Dictionary สำหรับจับคู่
country_map = {
    'นามิเบีย': 'NA', 'เนปาล': 'NP', 'เซนต์คิตส์และเนวิส': 'KN',
    'หมู่เกาะแฟโร': 'FO', 'แซมเบีย': 'ZM', 'กรีนแลนด์': 'GL',
    'เซนต์วินเซนต์และเกรนาดีนส์': 'VC', 'จิบูตี': 'DJ',
    'มอริเตเนีย': 'MR', 'ซูรินาเม': 'SR', 'เบลีซ': 'BZ',
    'เฟรนช์พอลินีเชีย': 'PF'
}

# 2. เติมค่าว่างใน countryID
df['countryID'] = df['countryID'].fillna(df['countryNameTH'].map(country_map))

# 3. ตรวจสอบ "นามิเบีย" เฉพาะเจาะจง
check_namibia = df[df['countryNameTH'] == 'นามิเบีย']
print(f"จำนวนแถวของนามิเบีย: {len(check_namibia)}")
print(f"จำนวนค่าว่างที่เหลือของนามิเบีย: {check_namibia['countryID'].isnull().sum()}")

# แสดงผล 5 แถวแรกของนามิเบีย
check_namibia[['countryNameTH', 'countryID', 'price', 'productDetailTH']].head()

จำนวนแถวของนามิเบีย: 25
จำนวนค่าว่างที่เหลือของนามิเบีย: 0

,countryNameTH,countryID,price,productDetailTH
5580,นามิเบีย,NA,16318673,ปลาแอลบาคอร์หรือทูน่าครีบยาวแช่เย็นจนแข็ง ไม่ร...
6118,นามิเบีย,NA,650647,ปลาทูน่าครีบเหลืองแช่เย็นจนแข็ง ไม่รวมเนื้อปลา...
6956,นามิเบีย,NA,382881,ปลาบิกอายทูนา แช่เย็นจนแข็ง ไม่รวมตับและไข่(Bi...
6991,นามิเบีย,NA,10206334,ปลาบิกอายทูนา แช่เย็นจนแข็ง ไม่รวมตับและไข่(Bi...
8366,นามิเบีย,NA,859142,ครีบปลาฉลาม (หูฉลาม)

เช็คความเรียบร้อย

In [ ]:
# เช็กค่าว่างสรุปสุดท้าย
print("--- สรุปจำนวนค่าว่างคงเหลือ ---")
print(df.isnull().sum())

data_table.enable_dataframe_formatter()
df.head(10)

--- สรุปจำนวนค่าว่างคงเหลือ ---
year               0
month              0
heading11          0
countryID          0
countryNameTH      0
weight             0
quantity           0
price              0
tradeflow          0
productDetailEN    0
productDetailTH    0
ETL_DATE           0
dtype: int64

,year,month,heading11,countryID,countryNameTH,weight,quantity,price,tradeflow,productDetailEN,productDetailTH,ETL_DATE
0,2568,8,1062000002,BJ,เบนิน,33,90,48080,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
1,2568,8,1062000002,MU,มอริเชียส,10,50,44147,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
2,2568,8,1062000002,BR,บราซิล,8,150,47068,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
3,2568,8,1062000002,EG,อียิปต์,315,100,225663,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
4,2568,9,1062000002,KE,เคนยา,49,200,74954,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
5,2568,9,1062000002,IT,อิตาลี,2,120,51917,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
6,2568,9,1062000002,SG,สิงคโปร์,5,2,6338,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
7,2568,1,1062000002,SC,เซเชลส์,200,20,169196,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
8,2568,2,1062000002,BJ,เบนิน,10,60,17170,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59
9,2568,2,1062000002,KE,เคนยา,25,100,39490,1,Turtles and snapping turtles live,เต่าและตะพาบน้ำมีชีวิต,12/3/2026 5:59

In [ ]:
import pandas as pd
import numpy as np

# 1. รวบรวมคำที่เป็นขยะ
garbage = ['', ' ', '  ', '#NAME?', 'nan', 'NaN', '(blank)', 'blank']

# 2. ตรวจสอบว่าแต่ละแถวมีปัญหาที่ฝั่งไหนบ้าง (สร้างเงื่อนไข True/False)
th_missing = df['productDetailTH'].astype(str).str.strip().isin(garbage) | df['productDetailTH'].isna()
en_missing = df['productDetailEN'].astype(str).str.strip().isin(garbage) | df['productDetailEN'].isna()

# 3. แยกกลุ่มปัญหาออกเป็น 3 กรณี
# กรณี 1: มีชื่ออังกฤษ แต่ "ไทยหาย"
only_th_missing = th_missing & ~en_missing

# กรณี 2: มีชื่อไทย แต่ "อังกฤษหาย" (กลุ่มเจ้าปัญหา)
only_en_missing = ~th_missing & en_missing

# กรณี 3: หายทั้งคู่ (บอดสนิท)
both_missing = th_missing & en_missing

# 4. สรุปผลให้กรรมการดู
print("--- 🔍 เจาะลึกปัญหา Data Missingness (ก่อนการ Clean) ---")
print(f"กรณีที่ 1 | มีชื่ออังกฤษ แต่ไม่มีชื่อไทย: {only_th_missing.sum():,} แถว")
print(f"กรณีที่ 2 | มีชื่อไทย แต่ไม่มีชื่ออังกฤษ: {only_en_missing.sum():,} แถว 🚨 (นี่คือสาเหตุที่ EN ยอดพุ่ง)")
print(f"กรณีที่ 3 | ไม่มีชื่อเลยทั้งสองภาษา: {both_missing.sum():,} แถว")

--- 🔍 เจาะลึกปัญหา Data Missingness (ก่อนการ Clean) ---
กรณีที่ 1 | มีชื่ออังกฤษ แต่ไม่มีชื่อไทย: 0 แถว
กรณีที่ 2 | มีชื่อไทย แต่ไม่มีชื่ออังกฤษ: 16,239 แถว 🚨 (นี่คือสาเหตุที่ EN ยอดพุ่ง)
กรณีที่ 3 | ไม่มีชื่อเลยทั้งสองภาษา: 34 แถว

In [ ]:
# 1. เช็คในคอลัมน์ภาษาไทย (TH)
print("[ภาษาไทย] ค่าดั้งเดิมที่พบ")
old_values_th = df_original['productDetailTH'].astype(str).value_counts()
for g in garbage:
    if g in old_values_th:
        print(f"พบค่า '{g}': {old_values_th[g]:,} รายการ")

print("" + "-"*30 + "")

# 2. เช็คในคอลัมน์ภาษาอังกฤษ (EN)
print("[ภาษาอังกฤษ] ค่าดั้งเดิมที่พบ")
old_values_en = df_original['productDetailEN'].astype(str).value_counts()
for g in garbage:
    if g in old_values_en:
        print(f"พบค่า '{g}': {old_values_en[g]:,} รายการ")

[ภาษาไทย] ค่าดั้งเดิมที่พบ
พบค่า '(blank)': 34 รายการ
------------------------------
[ภาษาอังกฤษ] ค่าดั้งเดิมที่พบ
พบค่า '#NAME?': 7,586 รายการ
พบค่า '(blank)': 8,689 รายการ

จะเห็นได้ว่าค่าที่ ไม่ระบุจริงจริงแล้วมีเพียง 34 รายการ และค่าอื่นที่เป็น missing value อาจจะเกิดจากการที่ไม่สามารถแทนคำเป็นภาษาอังกฤษในระบบหรือการเก็บข้อมูลที่ไม่ดี

In [ ]:
import numpy as np

# 1. ทำสำเนาข้อมูลเพื่อความปลอดภัย และลบคอลัมน์ EN ทิ้งไปเลย!
df_th_only = df.drop(columns=['productDetailEN'])

# 3. ล้างข้อมูลเฉพาะฝั่งภาษาไทย (TH)
df_th_only['productDetailTH'] = df_th_only['productDetailTH'].astype(str).str.strip().replace(garbage, np.nan)

# 4. เติมค่าที่แหว่งด้วยคำว่า 'ไม่ระบุประเภทสินค้า'
df_th_only['productDetailTH'] = df_th_only['productDetailTH'].fillna('ไม่ระบุประเภทสินค้า')

# 5. คำนวณผลลัพธ์ (จำนวนแถว และ มูลค่ารวม)
is_unknown = (df_th_only['productDetailTH'] == 'ไม่ระบุประเภทสินค้า')
count_unknown = is_unknown.sum()
price_unknown = df_th_only.loc[is_unknown, 'price'].sum()

print("--- สรุปผลจากการยึดภาษาไทยเป็นหลัก (Drop EN ทิ้ง) ---")
print(f"จำนวนรายการที่ไม่ระบุชื่อ: {count_unknown:,} แถว")
print(f"มูลค่าสินค้าที่ไม่ระบุชื่อสุทธิ: {price_unknown:,.2f} ล้านบาท")

--- สรุปผลจากการยึดภาษาไทยเป็นหลัก (Drop EN ทิ้ง) ---
จำนวนรายการที่ไม่ระบุชื่อ: 34 แถว
มูลค่าสินค้าที่ไม่ระบุชื่อสุทธิ: 15,649,945.00 ล้านบาท

ดังนั้นควรใช้ค่า productDetailTH เป็นหลักในการวิเคราะห์ข้อมูล เพราะค่าproductDetailENในdata setมีค่าmissing value ที่เยอะและยากต่อการนำไปใช้จึงสนในแค่ค่าproductDetailTH เพียงอย่างเดียว

In [ ]:
import pandas as pd

df['Trade_Type'] = df['tradeflow'].replace({1: 'Import', 2: 'Export', '1': 'Import', '2': 'Export'})

# 1. เช็ค Top 10 สินค้าส่งออก (Export - สินค้าทำเงิน)
print("🏆 TOP 10 สินค้าส่งออกที่ทำรายได้สูงสุดให้ไทย")
print("-" * 60)
top_export_products = df[df['Trade_Type'] == 'Export'].groupby('productDetailTH')['price'].sum().reset_index()
top_export_products = top_export_products.sort_values(by='price', ascending=False).head(10)

# แสดงผลแบบตัวเลขดูง่าย (format ใส่คอมม่า และทศนิยม 2 ตำแหน่ง)
top_export_products['price'] = top_export_products['price'].apply(lambda x: f"{x:,.2f}")
display(top_export_products)

print("\n\n")

# 2. เช็ค Top 10 สินค้านำเข้า (Import - สินค้าที่ไทยต้องซื้อเยอะสุด)
print("🛒 TOP 10 สินค้านำเข้าที่มีมูลค่าสูงสุด")
print("-" * 60)
top_import_products = df[df['Trade_Type'] == 'Import'].groupby('productDetailTH')['price'].sum().reset_index()
top_import_products = top_import_products.sort_values(by='price', ascending=False).head(10)

top_import_products['price'] = top_import_products['price'].apply(lambda x: f"{x:,.2f}")
display(top_import_products)

🏆 TOP 10 สินค้าส่งออกที่ทำรายได้สูงสุดให้ไทย
------------------------------------------------------------

                                       productDetailTH              price
110  ปลาทูน่า สคิปแจกและแอตแลนติกโบนิโตอื่นๆ ที่บรร...  61,081,061,321.00
288  อาหารสุนัขหรือแมวที่มีปลาบรรจุภาชนะที่อากาศเข้...  27,858,706,845.00
109  ปลาทูน่า สคิปแจกและแอตแลนติกโบนิโต ที่บรรจุภาช...  15,582,846,027.00
24      กุ้งขาว ไม่บรรจุภาชนะที่อากาศผ่านเข้าออกไม่ได้   8,206,304,934.00
40        ของผสมที่ใช้ปรุงรส และของผสมที่ใช้ชูรสอื่น ๆ   7,919,366,902.00
146                         ปลาหมึกกล้วย แช่เย็นจนแข็ง   6,365,859,423.00
18   กุ้งขาว (ลิปโทพิเนซัสวันนาไม) ลักษณะนอกเหนือจา...   5,354,940,084.00
304                                     เนื้อปลาซูริมิ   5,070,870,234.00
26                           กุ้งขาว ไม่มีหัว ไม่มีหาง   5,062,930,559.00
27                                        กุ้งชุบเกล็ด   4,991,734,258.00

🛒 TOP 10 สินค้านำเข้าที่มีมูลค่าสูงสุด
------------------------------------------------------------

                                       productDetailTH              price
124  ปลาสคิปแจ็คหรือปลาโอท้องแถบแช่เย็นจนแข็ง ไม่รว...  28,359,413,808.00
130                         ปลาหมึกกล้วย แช่เย็นจนแข็ง  16,618,848,954.00
99                                      ปลาทูน่าอื่น ๆ   9,346,295,168.00
97   ปลาทูน่าครีบเหลืองแช่เย็นจนแข็ง ไม่รวมเนื้อปลา...   8,575,489,505.00
145  ปลาอินเดียนแมคเคอเรล (ราสต์รีลลิเกอร์กานาเกอทา...   7,946,547,429.00
188                      ปลาแซลมอนแอตแลนติก สด แช่เย็น   7,386,140,247.00
35    ซูริมิ (เนื้อปลาบด) สด แช่เย็น หรือแช่เย็นจนแข็ง   4,362,174,620.00
187                ปลาแซลมอนแปซิฟิกอื่นๆ แช่เย็นจนแข็ง   4,007,476,661.00
206  ปลาแอลบาคอร์หรือทูน่าครีบยาวแช่เย็นจนแข็ง ไม่ร...   3,715,278,126.00
131          ปลาหมึกกล้วย แห้ง ใส่เกลือหรือแช่น้ำเกลือ   2,846,411,169.00

#🧠 ข้อ 1 — ตลาดส่งออกสินค้าประมงของไทยอยู่ที่ไหน?

เตรียมข้อมูลก่อนนำไปสร้างกราฟโดยดึงรหัสสินค้าแค่ 4 ตัวแรกมาใช้และกรองประเทศที่เป็นค่าขยะออกไป

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd

# 1. กรองประเทศที่เป็นค่าขยะออกไป (เก็บไว้ในตัวแปร df_valid เพื่อใช้ทำกราฟประเทศ)
garbage_countries = ['ไม่ระบุ', 'Unknown', 'nan', 'NaN', '0', '-']
#df_valid = df[~df['countryNameTH'].astype(str).isin(garbage_countries)]

# 2. สร้างคอลัมน์ 'HS' ดึงรหัสสินค้าแค่ 4 ตัวแรกมาใช้จัดกลุ่ม (โครงสร้างสินค้า)
df['HS'] = df['heading11'].astype(str).str[:4]

print("✅ เตรียมข้อมูล df พร้อมสำหรับทำโจทย์ทั้ง 3 ข้อแล้ว!")

✅ เตรียมข้อมูล df พร้อมสำหรับทำโจทย์ทั้ง 3 ข้อแล้ว!

# ประเทศใดเป็น ตลาดส่งออกสินค้าประมงสำคัญของไทย

In [ ]:
import pandas as pd
import plotly.express as px

# 1. เช็คและสร้าง Trade_Type ให้ชัวร์
if 'Trade_Type' not in df.columns:
    df['Trade_Type'] = df['tradeflow'].replace({1: 'Import', 2: 'Export', '1': 'Import', '2': 'Export'})

# 2. กรองประเทศขยะออกก่อน
garbage_countries = ['ไม่ระบุ', 'Unknown', 'nan', 'NaN', '0', '-']
df_valid = df[~df['countryNameTH'].astype(str).isin(garbage_countries)]

# 3. กรองเฉพาะข้อมูล "ส่งออก (Export)"
df_export = df_valid[df_valid['Trade_Type'] == 'Export']

# 4. จัดกลุ่มตาม "ประเทศ (countryNameTH)" และรวมมูลค่า
export_by_country = df_export.groupby('countryNameTH')['price'].sum().reset_index()
export_by_country = export_by_country.sort_values(by='price', ascending=False)

# ==========================================
# 🌟 แยก Top 5 ประเทศ กับ "อื่นๆ"
# ==========================================
# ดึง 5 ประเทศแรก
top5_countries_df = export_by_country.head(5).copy()

# ดึงยอดที่เหลือมาบวกรวมกันเป็น "อื่นๆ (Others)"
others_sum_country = export_by_country.iloc[5:]['price'].sum()
others_country_df = pd.DataFrame([{'countryNameTH': 'ประเทศอื่นๆ (Others)', 'price': others_sum_country}])

# นำมาต่อกัน
final_pie_country_df = pd.concat([top5_countries_df, others_country_df], ignore_index=True)


# ==========================================
# 🥧 สร้างกราฟวงกลม (Pie Chart)
# ==========================================
fig = px.pie(final_pie_country_df,
             values='price',
             names='countryNameTH',
             title='🌍 สัดส่วนมูลค่าการส่งออกสินค้าประมงไทย แยกตามประเทศปลายทาง (Top 5)',
             color_discrete_sequence=px.colors.sequential.Blues_r)

# ปรับแต่งการแสดงผล
fig.update_traces(
    textposition='inside',
    textinfo='percent+label',
    customdata=final_pie_country_df['price'].apply(lambda x: f"{x:,.2f} MB"),
    hovertemplate="<b>%{label}</b><br>มูลค่า: %{customdata}<br>สัดส่วน: %{percent}<extra></extra>",
    textfont=dict(size=14, color='white')
)

fig.update_layout(showlegend=False, height=600)

fig.show()

# พิมพ์สรุปข้อมูล
print("-" * 50)
print("📊 สรุปสัดส่วนตลาดส่งออก (Top 5):")
total_export = export_by_country['price'].sum()
for index, row in top5_countries_df.iterrows():
    percent = (row['price'] / total_export) * 100
    print(f"{index + 1}. {row['countryNameTH']}: {percent:.2f}% ({row['price']:,.2f} ล้านบาท)")
print("-" * 50)

--------------------------------------------------
📊 สรุปสัดส่วนตลาดส่งออก (Top 5):
95. สหรัฐอเมริกา: 21.94% (48,943,857,678.00 ล้านบาท)
32. ญี่ปุ่น: 14.93% (33,305,128,700.00 ล้านบาท)
24. จีน: 8.80% (19,645,801,373.00 ล้านบาท)
109. ออสเตรเลีย: 5.16% (11,518,362,442.00 ล้านบาท)
161. แคนาดา: 3.53% (7,880,610,315.00 ล้านบาท)
--------------------------------------------------

In [ ]:
# ==========================================
# 🇺🇸 เจาะลึกรายประเทศ: สหรัฐอเมริกา
# ==========================================
target_country = 'สหรัฐอเมริกา'

# กรองส่งออก และ กรองเฉพาะประเทศเป้าหมาย
df_target = df[(df['Trade_Type'] == 'Export') & (df['countryNameTH'] == target_country)]

# 🌟 คำนวณยอดส่งออกรวม "เฉพาะที่ส่งไปสหรัฐฯ"
total_target_value = df_target['price'].sum()

# จัดกลุ่มหา 5 สินค้าแรกที่ส่งไปประเทศนั้น
top5_target = df_target.groupby('productDetailTH')['price'].sum().reset_index()
top5_target = top5_target.sort_values(by='price', ascending=False).head(5)

# 🌟 สร้างคอลัมน์คิดเปอร์เซ็นต์ (เทียบกับยอดส่งออกไปสหรัฐฯ เท่านั้น)
top5_target['%_of_USA'] = (top5_target['price'] / total_target_value) * 100

# ฟอร์แมตตัวเลขให้ดูง่าย
top5_target['price'] = top5_target['price'].apply(lambda x: f"{x:,.2f}")
top5_target['%_of_USA'] = top5_target['%_of_USA'].apply(lambda x: f"{x:.2f}%")

# แสดงผลสหรัฐอเมริกา
print(f"TOP 5 สินค้าที่เราส่งออกไป '{target_country}' มากที่สุด")
print(f"(คิดสัดส่วนจากยอดส่งออกไป {target_country} รวม: {total_target_value:,.2f} ล้านบาท)")
print("-" * 70)
display(top5_target)

TOP 5 สินค้าที่เราส่งออกไป 'สหรัฐอเมริกา' มากที่สุด
(คิดสัดส่วนจากยอดส่งออกไป สหรัฐอเมริกา รวม: 48,943,857,678.00 ล้านบาท)
----------------------------------------------------------------------

,productDetailTH,price,%_of_USA
136,อาหารสุนัขหรือแมวที่มีปลาบรรจุภาชนะที่อากาศเข้...,"10,513,506,961.00",21.48%
56,ปลาทูน่า สคิปแจกและแอตแลนติกโบนิโตอื่นๆ ที่บรร...,"10,470,427,260.00",21.39%
55,ปลาทูน่า สคิปแจกและแอตแลนติกโบนิโต ที่บรรจุภาช...,"5,367,064,458.00",10.97%
14,กุ้งขาว ไม่บรรจุภาชนะที่อากาศผ่านเข้าออกไม่ได้,"3,139,333,742.00",6.41%
11,กุ้งขาว (ลิปโทพิเนซัสวันนาไม) ไม่มีหัว มีหาง แ...,"2,296,619,195.00",4.69%

สหรัฐอเมริกา คือขุมทรัพย์รายได้หลัก (Top Export: 21.48%)

ส่งออกไปสหรัฐฯ มากที่สุดเป็นอันดับหนึ่ง มูลค่าการส่งออก 10,513.50 ล้านบาท

> สหรัฐอเมริกาเป็นตลาดที่มี กำลังซื้อสูง และมีกฎระเบียบด้านสุขอนามัยที่เข้มงวด ซึ่งโรงงานแปรรูปของไทยมีความสามารถในการผลิตสินค้าที่ได้มาตรฐานสากลระดับสูง โดยเฉพาะสินค้ากลุ่ม อาหารสัตว์เลี้ยง (Pet Food) และ ทูน่ากระป๋อง ซึ่งเป็นที่ต้องการสูงมากในตลาดอเมริกา

# ประเทศใดเป็น แหล่งนำเข้าสัตว์น้ำหลักของไทย

In [ ]:
import pandas as pd
import plotly.express as px

# 1. เช็คและสร้าง Trade_Type ให้ชัวร์
if 'Trade_Type' not in df.columns:
    df['Trade_Type'] = df['tradeflow'].replace({1: 'Import', 2: 'Export', '1': 'Import', '2': 'Export'})

# 2. กรองประเทศขยะออกก่อน
garbage_countries = ['ไม่ระบุ', 'Unknown', 'nan', 'NaN', '0', '-']
df_valid = df[~df['countryNameTH'].astype(str).isin(garbage_countries)]

# 3. กรองเฉพาะข้อมูล "นำเข้า (Import)"
df_import = df_valid[df_valid['Trade_Type'] == 'Import']

# 4. จัดกลุ่มตาม "ประเทศ (countryNameTH)" และรวมมูลค่า
import_by_country = df_import.groupby('countryNameTH')['price'].sum().reset_index()
import_by_country = import_by_country.sort_values(by='price', ascending=False)

# ==========================================
# 🌟 แยก Top 5 ประเทศ กับ "อื่นๆ"
# ==========================================
# ดึง 5 ประเทศแรก
top5_import_countries = import_by_country.head(5).copy()

# ดึงยอดที่เหลือมาบวกรวมกันเป็น "อื่นๆ (Others)"
others_sum_import = import_by_country.iloc[5:]['price'].sum()
others_import_df = pd.DataFrame([{'countryNameTH': 'ประเทศอื่นๆ (Others)', 'price': others_sum_import}])

# นำมาต่อกัน
final_pie_import_df = pd.concat([top5_import_countries, others_import_df], ignore_index=True)


# ==========================================
# 🥧 สร้างกราฟวงกลม (Pie Chart)
# ==========================================
fig = px.pie(final_pie_import_df,
             values='price',
             names='countryNameTH',
             title='🛒 สัดส่วนมูลค่าการนำเข้าสินค้าประมงไทย แยกตามประเทศต้นทาง (Top 5)',
             color_discrete_sequence=px.colors.sequential.Oranges_r) # ใช้โทนสีส้มสำหรับฝั่งนำเข้า

# ปรับแต่งการแสดงผล
fig.update_traces(
    textposition='inside',
    textinfo='percent+label',
    customdata=final_pie_import_df['price'].apply(lambda x: f"{x:,.2f} MB"),
    hovertemplate="<b>%{label}</b><br>มูลค่า: %{customdata}<br>สัดส่วน: %{percent}<extra></extra>",
    textfont=dict(size=14, color='white')
)

fig.update_layout(showlegend=False, height=600)

fig.show()

# พิมพ์สรุปข้อมูลให้เอาไปใช้พูดพรีเซนต์
print("-" * 50)
print("📊 สรุปสัดส่วนแหล่งนำเข้า (Top 5):")
total_import = import_by_country['price'].sum()
for index, row in top5_import_countries.iterrows():
    percent = (row['price'] / total_import) * 100
    print(f"{index + 1}. {row['countryNameTH']}: {percent:.2f}% ({row['price']:,.2f} ล้านบาท)")
print("-" * 50)

--------------------------------------------------
📊 สรุปสัดส่วนแหล่งนำเข้า (Top 5):
16. จีน: 13.03% (19,858,082,468.00 ล้านบาท)
24. นอร์เวย์: 8.90% (13,563,584,579.00 ล้านบาท)
72. อินเดีย: 7.69% (11,726,777,398.00 ล้านบาท)
100. เวียดนาม: 7.27% (11,081,190,095.00 ล้านบาท)
120. ไต้หวัน: 5.94% (9,058,458,951.00 ล้านบาท)
--------------------------------------------------

In [ ]:
# ==========================================
# 🇨🇳 ส่วนที่ 2: เจาะจงจีน (พร้อมสัดส่วน % เมื่อเทียบกับยอดของจีนเอง)
# ==========================================
target_country = 'จีน'
df_import_china = df_import_all[df_import_all['countryNameTH'] == target_country]

# 🌟 คำนวณยอดนำเข้ารวม "เฉพาะจากจีน"
total_import_china = df_import_china['price'].sum()

top5_china = df_import_china.groupby('productDetailTH')['price'].sum().reset_index()
top5_china = top5_china.sort_values(by='price', ascending=False).head(5)

# 🌟 สร้างคอลัมน์ % (เทียบกับยอดรวมของจีน)
top5_china['%_of_China'] = (top5_china['price'] / total_import_china) * 100

# แต่งตัวเลขให้สวยงาม
top5_china['price'] = top5_china['price'].apply(lambda x: f"{x:,.2f}")
top5_china['%_of_China'] = top5_china['%_of_China'].apply(lambda x: f"{x:.2f}%")

print(f"🇨🇳 TOP 5 สินค้าที่นำเข้าจาก '{target_country}'")
print(f"(คิดสัดส่วนจากยอดนำเข้าจากจีนรวม: {total_import_china:,.2f} ล้านบาท)")
print("-" * 70)
display(top5_china)

🇨🇳 TOP 5 สินค้าที่นำเข้าจาก 'จีน'
(คิดสัดส่วนจากยอดนำเข้าจากจีนรวม: 19,858,082,468.00 ล้านบาท)
----------------------------------------------------------------------

,productDetailTH,price,%_of_China
29,ปลาทูน่าอื่น ๆ,"6,537,453,557.00",32.92%
41,ปลาหมึกกล้วย แช่เย็นจนแข็ง,"4,045,197,469.00",20.37%
69,ปลาแปซิฟิกแมคเคอเรล (สคอมเบอร์จาโพนิกัส),"1,360,480,263.00",6.85%
76,ปลาแอลบาคอร์หรือทูน่าครีบยาวแช่เย็นจนแข็ง ไม่ร...,"947,534,838.00",4.77%
40,ปลาหมึกกระดองและปลาหมึกกล้วยอื่น ๆ ที่ไม่บรรจุ...,"612,414,460.00",3.08%

**จีน คือแหล่งวัตถุดิบหลัก (13.03%) หนึ่งในนั้นคือ ปลาทูน่า (32.92%) ของการนำเข้า**

ไทยนำเข้าจากจีนมากที่สุด คิดเป็นมูลค่า 19,858.08 ล้านบาท

>เพราะจีนเป็น แหล่งวัตถุดิบ (Raw Material Source) ขนาดใหญ่ที่มีราคาถูกและหลากหลาย ทั้งยังมีข้อได้เปรียบเรื่อง ระยะทางขนส่งที่ใกล้ไทย ทำให้โรงงานแปรรูปของไทยเลือกนำเข้าวัตถุดิบจากจีนเพื่อลดต้นทุนการผลิตให้ต่ำที่สุดจึงทำให้จีนเป็นประเทศที่ไทยเลือกที่จะนำเข้าสินค้าประมงอันดับ1ของประเทศไทย

# ประเทศใดที่ไทย เกินดุลหรือขาดดุลการค้า ด้านสินค้าประมงอย่างชัดเจน

In [ ]:
# --- ส่วนที่ 3: ดุลการค้า (Trade Balance) ---
# รวมยอดส่งออกทุกประเทศ
all_export = df_export.groupby('countryNameTH')['price'].sum().reset_index().rename(columns={'price': 'Export'})
# รวมยอดนำเข้าทุกประเทศ
all_import = df_import.groupby('countryNameTH')['price'].sum().reset_index().rename(columns={'price': 'Import'})

# นำตารางส่งออกและนำเข้ามาเชื่อมกันด้วยชื่อประเทศ (ถ้าไม่มีข้อมูลฝั่งไหนให้เติมเลข 0)
df_trade = pd.merge(all_export, all_import, on='countryNameTH', how='outer').fillna(0)
# คำนวณดุลการค้า (ส่งออก - นำเข้า)
df_trade['Trade_Balance'] = df_trade['Export'] - df_trade['Import']

# เลือก 5 ประเทศที่ไทยได้กำไรสูงสุด (เกินดุล) และ 5 ประเทศที่ไทยขาดทุนสูงสุด (ขาดดุล)
top_surplus = df_trade.nlargest(5, 'Trade_Balance')
top_deficit = df_trade.nsmallest(5, 'Trade_Balance')
df_balance = pd.concat([top_surplus, top_deficit]).sort_values('Trade_Balance')

# สร้างกราฟแท่งแสดงดุลการค้า
fig3 = px.bar(df_balance, y='countryNameTH', x='Trade_Balance', orientation='h',
              title='⚖️ ดุลการค้าสินค้าประมง (ไทยได้เปรียบ vs เสียเปรียบ)',
              color='Trade_Balance', color_continuous_scale='RdBu', # ใช้สี แดง-น้ำเงิน
              labels={'Trade_Balance': 'ดุลการค้าสุทธิ (ล้านบาท)', 'countryNameTH': 'ประเทศ'})
fig3.show()

#ไทยส่งออกอะไรไป "สหรัฐฯ" จนเกินดุลมหาศาล?
สหรัฐฯ คือตลาดที่ไทย เกินดุลการค้า (Net Export) สูงที่สุด สินค้าที่เป็น "เดอะแบก" ทำเงินเข้าประเทศมี 2 กลุ่มหลักครับ:

> อาหารสัตว์เลี้ยง (Pet Food - HS 2309): นี่คือพระเอกตัวจริง! สหรัฐฯ มีประชากรหมาแมวเยอะมาก และไทยคือผู้ผลิตอาหารสัตว์เลี้ยงจากปลาทูน่าระดับโลก สินค้ากลุ่มนี้มี Value Added (มูลค่าเพิ่ม) สูงกว่าปลาสดหลายเท่า

> ปลาทูน่ากระป๋อง/แปรรูป (Prepared Tuna - HS 1604): ไทยเป็นเจ้าตลาดในสหรัฐฯ มาอย่างยาวนาน เพราะโรงงานในไทยมีมาตรฐานการผลิตที่ยอมรับในระดับสากล



สาเหตุที่เกินดุลชัดเจน เพราะสหรัฐฯ เน้น "บริโภค" สินค้าสำเร็จรูปจากเรา แต่เราแทบไม่ได้ "นำเข้า" วัตถุดิบประมงจากเขาเลย (เพราะค่าขนส่งแพงและชนิดปลาไม่ตรงความต้องการโรงงานไทย ที่ต้องการปลาที่มาจากจีน(32.92%ของสินค้าที่นำเข้ามา) ใช้เพื่ออุตสาหกรรมปลากระป๋องที่เป็นอุตสาหกรรมที่ใหญ่เป็นอันดับต้นของไทย)

---

# สินค้าใดที่เป็นต้นเหตุให้เราขาดดุล (แต่คนไทยชอบกินมาก)

> ปลาแซลมอนและเทราต์ (Fresh/Frozen Salmon - HS 0302, 0303): นอร์เวย์คือแหล่งฟาร์มแซลมอนที่ใหญ่ที่สุดในโลก สินค้ากลุ่มนี้มี ราคาสูงมากต่อหน่วย เมื่อเทียบกับปลาชนิดอื่น และเราไม่สามารถเลี้ยงให้เจริญเติบโตได้ภายในประเทศ


>ปลาแมกเคอเรลนอร์เวย์ (Saba): ที่เรากินในร้านอาหารญี่ปุ่นส่วนใหญ่ก็นำเข้าจากแถบสแกนดิเนเวีย


สาเหตุที่ขาดดุลชัดเจน เพราะนอร์เวย์ส่งออก "สินค้าพรีเมียมราคาแพง" มาให้เรา แต่คนนอร์เวย์แทบไม่บริโภคปลากระป๋องหรืออาหารสัตว์เลี้ยงจากไทยเลย ดุลการค้าฝั่งประมงระหว่างไทย-นอร์เวย์ จึงเป็นสีแดงเข้ม (ขาดดุล) เสมอครับ

# 🦐 ข้อ 2 — สินค้าประมงชนิดใดคือหัวใจของการค้าไทย?

In [ ]:
import plotly.graph_objects as go
import pandas as pd

# ==========================================
# 1. เตรียมข้อมูล (Preparation)
# ==========================================

# 🌟 จัดกลุ่มตาม HS Code: สร้างคอลัมน์รหัสสินค้า 4 หลักแรก (HS) จากรหัสเต็ม 11 หลัก
df['HS'] = df['heading11'].astype(str).str[:4]


# ==========================================
# 2. คำนวณมูลค่า (Aggregation & Calculation)
# ==========================================

# A. สรุปยอด "ส่งออก" ตามรหัส HS (และดึงชื่อสินค้ามาด้วยเพื่อความเข้าใจง่าย)
# เราจะเลือกชื่อสินค้าที่มียอดส่งออกสูงสุดในรหัสนั้นๆ มาแสดงเป็นชื่อหมวด
hs_export = df[df['Trade_Type'] == 'Export'].groupby(['HS', 'productDetailTH'])['price'].sum().reset_index()
hs_export = hs_export.sort_values('price', ascending=False).drop_duplicates('HS').rename(columns={'price': 'Export'})

# B. สรุปยอด "นำเข้า" ตามรหัส HS
hs_import = df[df['Trade_Type'] == 'Import'].groupby('HS')['price'].sum().reset_index().rename(columns={'price': 'Import'})

# C. นำข้อมูลส่งออกและนำเข้ามาเชื่อมกัน (Merge) ด้วยรหัส HS
df_hs = pd.merge(hs_export, hs_import, on='HS', how='outer').fillna(0)

# D. คำนวณมูลค่าการค้าสุทธิ (Net Trade = ส่งออก - นำเข้า)
df_hs['Net_Trade'] = df_hs['Export'] - df_hs['Import']

# E. หามูลค่าการค้ารวม (Total Trade) เพื่อคัดเอาเฉพาะ 15 หมวดสินค้าที่มีบทบาทเยอะสุดมาแสดง
df_hs['Total_Trade'] = df_hs['Export'] + df_hs['Import']
top_hs = df_hs.nlargest(15, 'Total_Trade').sort_values('Net_Trade')


# ==========================================
# 3. สร้างกราฟ (Visualization)
# ==========================================

# สร้างกราฟแท่งแนวนอน
fig = go.Figure()

fig.add_trace(go.Bar(
    # แกน Y: แสดงรหัส HS คู่กับชื่อสินค้า (ตัดชื่อยาวๆ ให้เหลือ 40 ตัวอักษร)
    y=top_hs['HS'] + " " + top_hs['productDetailTH'].astype(str).str[:40],
    x=top_hs['Net_Trade'],
    orientation='h',
    # 🌟 ทีเด็ด: กำหนดสีแยกตามค่าสุทธิ: สีเขียว = เกินดุล (ส่งออกสุทธิ), สีแดง = ขาดดุล (นำเข้าสุทธิ)
    marker_color=top_hs['Net_Trade'].apply(lambda x: '#2ca02c' if x > 0 else '#d62728'),
    # แสดงตัวเลขบนแท่งกราฟแบบย่อหน่วย (เช่น 1.5k)
    text=top_hs['Net_Trade'].apply(lambda x: f"{x/1000:,.1f}k" if abs(x) >= 1000 else f"{x:,.1f}"),
    textposition='auto'
))

# ปรับแต่งหน้าตากราฟ
fig.update_layout(
    title='📦 โครงสร้างสินค้าประมงไทย (Net Export vs Net Import)',
    xaxis_title='มูลค่าสุทธิ (ล้านบาท) [🟢 เขียว=เกินดุล (ได้เงิน), 🔴 แดง=ขาดดุล (เสียเงิน)]',
    yaxis_title='หมวดสินค้า (รหัส HS)',
    plot_bgcolor='rgba(0,0,0,0)', # พื้นหลังโปร่งใส
    height=600 # ปรับความสูงกราฟให้พอดีกับ 15 รายการ
)

# แสดงกราฟ
fig.show()

**🟢 สินค้าที่เป็น Net Export (ส่งออกสุทธิ)
คือกลุ่มสินค้าที่ไทย "เก่ง" ในการแปรรูปและสร้างมูลค่าเพิ่ม (Value Added) จนมียอดขายไปต่างประเทศสูงกว่าที่ซื้อเข้ามามาก**

HS 1604: ปลาปรุงแต่งหรือทำคั่วคาว (เช่น ทูน่ากระป๋อง) * นี่คือ "พระเอก" ตัวจริงของไทย เราส่งออกมหาศาล ขณะที่นำเข้าน้อยมาก เพราะเราเป็นโรงงานปลากระป๋องของโลก

HS 2309: อาหารสำหรับสัตว์เลี้ยง (Pet Food)
สินค้าดาวรุ่งที่มียอดส่งออกสูงมาก โดยใช้เนื้อปลาเป็นส่วนประกอบหลัก เป็นกลุ่มที่ไทยเกินดุลการค้าอย่างชัดเจน ! ! !

 ---

**🔴 สินค้าที่เป็น Net Import (นำเข้าสุทธิ)
คือกลุ่มสินค้าที่เรา "พึ่งพา" ต่างประเทศ ส่วนใหญ่เป็นวัตถุดิบต้นน้ำเพื่อเอามาใช้ในโรงงาน หรือสินค้าเกรดพรีเมียมที่ในไทยไม่มี:**

HS 0303: ปลาแช่แข็ง (เช่น ทูน่าแช่แข็ง Skipjack/Yellowfin)
เราพึ่งพาการนำเข้าสูงที่สุด เพราะต้องนำมาใช้เป็น "วัตถุดิบ" ป้อนโรงงานปลากระป๋อง (ยิ่งนำเข้าปลาเยอะ แปลว่าจะสามารถส่งออกปลากระป๋องได้เยอะตาม)

HS 0302: ปลาสดหรือแช่เย็น (เช่น แซลมอน)
สินค้าพรีเมียมสำหรับการบริโภคโดยตรงที่ไทยไม่สามารถผลิตเองได้ในเชิงอุตสาหกรรม

HS 0307: สัตว์น้ำจำพวกโมลลุสก์ (เช่น ปลาหมึกแช่แข็ง)
นำเข้าเพื่อใช้ทั้งในอุตสาหกรรมร้านอาหารและการแปรรูปเบื้องต้น



> "เรานำเข้า วัตถุดิบแช่แข็ง (Net Import) จากทั่วโลก เพื่อเอามาใช้ในการผลิตและการจัดการในประเทศ แปรรูปให้กลายเป็น สินค้ามูลค่าสูง (Net Export) แล้วส่งออกไปขายทั่วโลก โดยเฉพาะตลาดใหญ่อย่างสหรัฐอเมริกาและญี่ปุ่น"

# 📈 ข้อ 3 — การค้าสัตว์น้ำมีฤดูกาลหรือไม่?

* แนวโน้มการเปลี่ยนแปลงของ Import และ Export สินค้าประมง
* ระบุให้ได้ว่าเดือนใดคือ ช่วงการค้าสูงสุด (Peak) ช่วงการค้าต่ำสุด (Low)

In [ ]:
import plotly.express as px
import pandas as pd

# 1. เช็คและสร้าง Trade_Type ให้ชัวร์
if 'Trade_Type' not in df.columns:
    df['Trade_Type'] = df['tradeflow'].replace({1: 'Import', 2: 'Export', '1': 'Import', '2': 'Export'})

# 2. จัดกลุ่มข้อมูลตาม 'เดือน' และ 'ประเภทการค้า' แล้วรวมมูลค่า
monthly_trade = df.groupby(['month', 'Trade_Type'])['price'].sum().reset_index()น

# 3. สร้างกราฟเส้น (Line Chart)
fig = px.line(monthly_trade, x='month', y='price', color='Trade_Type', markers=True,
              title='📈 ฤดูกาลการค้าสินค้าประมงไทย ปี 2568 (Seasonality)',
              labels={'month': 'เดือน', 'price': 'มูลค่าการค้า (ล้านบาท)', 'Trade_Type': 'ประเภท'},
              color_discrete_map={'Export': '#2ca02c', 'Import': '#d62728'})

# 4. ฟังก์ชันหาจุด Peak และ Low อัตโนมัติ เพื่อทำ Annotation ชี้เป้า
for trade_type in ['Export', 'Import']:
    data_subset = monthly_trade[monthly_trade['Trade_Type'] == trade_type]
    if not data_subset.empty:
        peak_idx = data_subset['price'].idxmax()
        low_idx = data_subset['price'].idxmin()

        peak_month, peak_val = data_subset.loc[peak_idx, 'month'], data_subset.loc[peak_idx, 'price']
        low_month, low_val = data_subset.loc[low_idx, 'month'], data_subset.loc[low_idx, 'price']

        # วาดป้ายชี้จุด Peak
        fig.add_annotation(x=peak_month, y=peak_val,
                           text=f"🏆 Peak ({peak_val/1000:,.1f}k)",
                           showarrow=True, arrowhead=2, ay=-40)
        # วาดป้ายชี้จุด Low
        fig.add_annotation(x=low_month, y=low_val,
                           text=f"📉 Low ({low_val/1000:,.1f}k)",
                           showarrow=True, arrowhead=2, ay=40)

# 5. แมปตัวเลขแกน X ให้แสดงเป็นชื่อเดือนภาษาไทย
month_names_th = ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.']

fig.update_layout(
    xaxis=dict(
        tickmode='array',
        tickvals=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], # ตำแหน่งตัวเลขเดิม 1-12
        ticktext=month_names_th # ข้อความที่จะเอาไปแปะทับ
    ),
    plot_bgcolor='rgba(0,0,0,0)',
    yaxis_gridcolor='lightgray'
)

fig.show()

# 🔴 1. กราฟฝั่ง "นำเข้า" (Import) : "การเตรียมพร้อมก่อนช่วงวิกฤตวัตถุดิบขาดแคลน"

มกราคม (Peak): เพื่อคุ้มครองสัตว์น้ำมีไข่และวางไข่เลี้ยงตัวอ่อน (มักเริ่มช่วง ก.พ. - พ.ค.)

เหตุผล:

>โรงงานแปรรูปขนาดใหญ่ต้องเร่งนำเข้าวัตถุดิบปลาแช่แข็งจากต่างประเทศมาเก็บในห้องเย็น (Cold Storage) ให้ได้มากที่สุดในเดือนมกราคม เพื่อให้สายการผลิตทำงานได้ต่อเนื่องในช่วงที่เรือประมงไทยหยุดออกเรือ

* ที่มา: ประกาศกรมประมงเรื่อง "มาตรการปิดอ่าวไทย"

---

สิงหาคม (Low): เริ่มเปลี่ยนมาใช้สินค้าภายในประเทศเห็นได้จากการเปิดอ่าวดละกราฟที่ค่อยค่อยลดลงหลังจาการเปิดอ่าวช่วงพฤษภาคม


เหตุผล:
>เมื่อเข้าสู่เดือนสิงหาคม อ่าวไทยเปิดเต็มรูปแบบและเป็นช่วงหน้าฝนที่แพลงก์ตอนสมบูรณ์ สัตว์น้ำในประเทศจะ "ล้นตลาด" ทำให้โรงงานลดการนำเข้าและหันมาซื้อวัตถุดิบราคาถูกในประเทศแทน ยอดนำเข้าจึงดิ่งลงต่ำสุด

* ที่มา: "ฤดูกาลเปิดอ่าว" และวงจรชีวิตสัตว์น้ำในเขตมรสุม

---

# 🟢 2. ที่มาและเหตุผลฝั่ง "ส่งออก" (Export)
หัวใจหลัก: "การเก็บเกี่ยวออเดอร์จากงานแสดงสินค้าโลก"

พฤษภาคม (Peak):

(งานแสดงสินค้าอาหารที่ใหญ่ที่สุดในเอเชีย จัดที่ไทยทุกปลายเดือน พ.ค.)

เหตุผล:
> เป็นเดือนที่คู่ค้าทั่วโลกเดินทางมาเจรจาธุรกิจและสรุปคำสั่งซื้อล็อตใหญ่ ยอดส่งออกจึงพุ่งสูงที่สุดจากการระบายสต็อกสินค้าพรีเมียมและออเดอร์ล่วงหน้าที่รอการส่งมอบในช่วงงานนี้ทำให้กราฟจะมีความสูงที่สุดในช่วงนี้

* ที่มา: ปฏิทินงาน "THAIFEX - Anuga Asia"

---

มิถุนายน (Low):


เหตุผล:
>หลังจากเร่งส่งออกมหาศาลในเดือน พ.ค. จะเกิดช่วงสุญญากาศในเดือน มิ.ย. เนื่องจากสินค้าล็อตใหม่ยังอยู่ในกระบวนการผลิต (หลังได้วัตถุดิบจากการเปิดอ่าวกลางเดือน พ.ค.) และตลาดต่างประเทศอยู่ในช่วงรอรับสินค้า (In-transit) ยอดขายจึงวูบลงชั่วคราว

* ที่มา: "Processing & Logistics Gap" และช่วงรอยต่อฤดูกาล

---

#🔄 3. ความสัมพันธ์ระหว่าง 2 ช่วงเวลา (Relationship)ความสัมพันธ์ของกราฟนี้คือรูปแบบ "Stock & Sell Cycle" (วงจรตุนเพื่อขาย)

ความสัมพันธ์เชิงเวลา (Time-Lag): คุณจะเห็นว่าเรา "นำเข้า Peak ในเดือน 1" (ตุนวัตถุดิบ) เพื่อที่จะนำมาผลิตและ "ส่งออก Peak ในเดือน 5" (ขายสินค้าสำเร็จรูป)

>ช่วงเวลาที่ห่างกัน 4 เดือน คือ **Lead Time** มาตรฐานของอุตสาหกรรม (1 เดือนขนส่ง + 2 เดือนแปรรูป + 1 เดือนเตรียมส่งออก)

>ความสัมพันธ์เชิงทดแทน (Substitution): ในเดือน สิงหาคมที่ Import ต่ำสุด คือช่วงที่ความต้องการวัตถุดิบถูกทดแทนด้วยสัตว์น้ำในประเทศ (Local Supply)หลังจากการเปิดอ่าวในเดือนพฤษภาคมจึงทำให้กราฟลดลงเรื่อยเรื่อยจนถึงเดือนสิงหาคมก่อนที่จะเพื่อมสูงขึ้นอีกครั้งเพื่อเตรียมรับเทศกาลช่วงท้ายปี

**📑 ที่มาของข้อมูลอ้างอิง (Data Sources)**
* มาตรการปิดอ่าว: ประกาศกรมประมง กระทรวงเกษตรและสหกรณ์
* สถิติการค้า: กรมเจรจาการค้าระหว่างประเทศ (DTN) และ ศูนย์เทคโนโลยีสารสนเทศและการสื่อสาร สำนักงานปลัดกระทรวงพาณิชย์
* ปฏิทินกิจกรรม: กรมส่งเสริมการค้าระหว่างประเทศ (DITP) สำหรับงาน THAIFEX

#📈 ภาพรวมของข้อมูลการนำเข้า–ส่งออกสินค้าประมงของประเทศไทย

* ในปี 2568 อุตสาหกรรมประมงไทยแสดงศักยภาพอย่างโดดเด่นด้วยยอดเกินดุลการค้าสูงถึง 43,435.77 ล้านบาท โดยมีผลิตภัณฑ์อาหารกระป๋องและอาหารสัตว์เลี้ยงเป็นฟันเฟืองหลักในการขับเคลื่อนการส่งออก ซึ่งได้รับอานิสงส์สำคัญจากเทรนด์ **Pet Humanization** ในสหรัฐอเมริกา ที่ผู้บริโภคดูแลสัตว์เลี้ยงเสมือนสมาชิกในครอบครัว ส่งผลให้สหรัฐฯ ครองตำแหน่งตลาดส่งออกอันดับหนึ่งด้วยมูลค่าสูงถึง 48,943.85 ล้านบาท (คิดเป็นร้อยละ 21.94 ของมูลค่ารวม) อย่างไรก็ตาม ผลการวิเคราะห์ชี้ให้เห็นถึงความเสี่ยงเชิงยุทธศาสตร์จากการพึ่งพาการนำเข้าวัตถุดิบจากจีนเป็นหลัก เนื่องจากข้อดีด้านราคาและต้นทุนโลจิสติกส์ ซึ่งอาจส่งผลกระทบโดยตรงต่อความมั่นคงของซัพพลายเชน หากเกิดการเปลี่ยนแปลงด้านนโยบายหรือการตั้งกำแพงภาษี ดังนั้น แนวทางในอนาคตไทยจึงควรเร่งกระจายความเสี่ยงผ่านกลยุทธ์ Market Diversification เพื่อเฟ้นหาแหล่งวัตถุดิบสำรอง ควบคู่ไปกับการพัฒนานวัตกรรมอาหารสัตว์เชิงฟังก์ชัน (Functional Food) และการสร้างแบรนด์ของตนเอง เพื่อยกระดับประเทศไทยสู่การเป็น 'Global Health Hub' สำหรับสัตว์เลี้ยงโลกที่เติบโตได้อย่างยั่งยืนและมีอิสระทางการค้าอย่างแท้จริง